### ISSUE TITLE
IPv6 Support

### ISSUE THREAD

**Issue by alaslums** [cloudposse/terraform-aws-dynamic-subnets#21]
Hi,

I don't know if this is of interest, but I've added rudimentary IPv6 support in a fork of the repo:

https://github.com/everycity/terraform-aws-dynamic-subnets
https://github.com/everycity/terraform-aws-vpc

Wasn't sure what the best way to communicate this to the world was, hence raising an issue! Anyway thanks for the awesome work - really helpful template.

Cheers,

Alasdair

**Comment by osterman** [comment]
@alaslums awesome! thanks for sharing. @aknysh can you check it out and see how could incorporate his changes? Looks like they are pretty minimal. My concern would be that it doesn't look like we can easily enable/disable IPv6 support due to the egress rules. Perhaps they are harmless to keep around even if IPv6 support is disabled.

**Comment by aknysh** [comment]
thank you @alaslums.
we'll test, and if no issues, will add the changes to our repos

**Comment by osterman** [comment]
@aknysh can you follow up

**Comment by aknysh** [comment]
i'm on it, sorry for the delay

**Comment by razorsedge** [comment]
Any updates on getting IPv6 support?

**Comment by marekmoscichowski** [comment]
I opened #139 with @alaslums changes.
