### ISSUE TITLE
Add a simple way to just use all AZs

### ISSUE THREAD

**Issue by lvh** [cloudposse/terraform-aws-dynamic-subnets#36]
The existence of `length(data.aws_availability_zones.available.names)` implies that something already knows what "all AZs" or "n AZs" should look like; but I still have to specify an explicit list.

**Comment by osterman** [comment]
We used always just create subnets in all AZs, but there are some implicates with this:

1. If using private subnets with NAT gateways, cost goes up signficiantly since each AZ gets it's own gateway. This is required for true HA.
2. Some regions have a lot of AZs - I think up to 7. Amazon takes AZs out of commission. When that happens, the subnet calculations change which causes a destructive rebuild of the entire environment. This is not usually desirable and terraform is not good at handling situations where a list of values changes. It always wants to destroy and recreate.
3. Operating in a lot of AZs increases latencies and inter-zone data transfer costs if there's a lot of chatter between instances. If there are fewer AZs, it's easier to ensure more intrazone routing. 
4. Historically, it used to be that you had to purchase RIs in an AZ, so having more AZs made it more difficult to forecast where to buy RIs. I don't think this is the case anymore.

**Comment by osterman** [comment]
> The existence of length(data.aws_availability_zones.available.names) implies that something already knows what "all AZs" or "n AZs" should look like

The reason we have the data provider right now is so we can calculate subnets based on the theoretical max so that a user can add remove subnets without it affecting the subnet calculation, which causes terraform to want to rebuild.

**Comment by Jamie-BitFlight** [comment]
This PR addresses both scenarios. Allowing for max subnets to be set. Or a number of public/private subnets to be set. To specify a list of named az's or just go with the full list of az's.
