### ISSUE TITLE
Subnet count is not relative to the "selected" availability zones but "all available"

### ISSUE THREAD

**Issue by toabi** [cloudposse/terraform-aws-dynamic-subnets#88]
Maybe we just misread the documentation, but this caused some discussion and confusion in our team.

We thought this module will spread the subnets over the given AZs.
We gave it a `/23` and two `availability_zones`, so we expected it would create 4 `/26` blocks, but it always put out some weird `/27` cidr blocks.

After reading the code there: 

https://github.com/cloudposse/terraform-aws-dynamic-subnets/blob/7d3182d8c3b5fe581042c367c4859a8091e321d4/private.tf#L13-L15

What's the reason that the calculation doesn't use the provided availability_zones?

**Comment by Nuru** [comment]
This is intentional behavior that escaped documentation in the README.

Subnets are "pets": very long lived and difficult to part with. Once you have a subnet created, you put a lot of resources in it. In order to change the subnet CIDR, you have to delete everything in the subnet, delete the subnet, and then create a new subnet. This is very painful and we learned this the hard way.

So this module takes the position that the private IP address space is big enough to reserve some of it for future expansion. By default it divides the CIDR into pieces it can reserve for each availability zone currently available. This way, if you decide later you want to use an availability zone you are not using now, you will not have to adjust the existing subnets.

We even provide `var.max_subnet_count` so you can reserve room for future expansion, as when a region goes from 2 to 3 or from 3 to 4 AZs. The region may have 2 AZs now, but you want to use 3 when the third becomes available, so you set `var.max_subnet_count = 3`. On the other side of the problem, you can use `var.max_subnet_count` to limit the number of subnets to fewer than the number of AZs. For example, you my decide you only want to use 3 AZs even if you are in a region with 5 AZs, reasoning that 3 are cheaper than 5 and 3 provides enough redundancy so  you will never want/need 5. So in this case you can set `var.max_subnet_count = 3` and the module will divide the CIDR among 3 AZs instead of the default 5.
